baseURL: "https://0xd0cf11e.github.io"
title: sud0suw
author: Suweera De Souza
#copyright: 'Hugo theme by © 2020, Andrey Parfenov'
paginate: 4
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
footnoteReturnLinkContents: ^
theme: origin
# To learn more about hosting on github
# - https://gohugo.io/hosting-and-deployment/hosting-on-github/
# - https://inside.getambassador.com/creating-and-deploying-your-first-hugo-site-to-github-pages-1e1f496cf88d
publishDir: "0xd0cf11e.github.io"
params:
  description: simple hugo theme
  featured: true
  cssonly: true
  socials:
    #facebook: ''
    twitter: 'https://twitter.com/sud0suw'
    #instagram: ''
    #youtube: ''
    github: 'https://github.com/0xd0cf11e'
    #gitlab: ''
    linkedin: 'https://www.linkedin.com/in/suweera-de-souza-b5216321'
    #slack: ''
    #stackoverflow: ''
    #medium: ''
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
taxonomies:
  category: categories
  tag: tags
  series: series
markup:
  highlight:
    style: github
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true