baseUrl: "https://0xd0cf11e.github.io"
languageCode: en-us
theme: terminal
paginate: 5
publishDir: "0xd0cf11e.github.io"

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: pink
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: false

languages:
  en:
    languageName: English
    title: Title
    subtitle: sudosu
    keywords: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: sudosu
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: About
        url: /about

